### ISSUE TITLE
return variable info

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/cdatweb#106]
Right now the server cdat.get_variable only returns all the variable names in a .inc file.

all information about each variable in needed

![screen shot 2016-03-30 at 8 28 26 am](https://cloud.githubusercontent.com/assets/438922/14151677/e275b588-f663-11e5-8661-bbc74425f8ac.png)

**Comment by danlipsa** [comment]
https://github.com/UV-CDAT/cdatweb/pull/108
