### ISSUE TITLE
plot part of a variable

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/cdatweb#107]
currently cdat.get_plot takes a variable

needed is the ability to generate a plot with a subset of the variable

![screen shot 2016-03-30 at 8 28 14 am](https://cloud.githubusercontent.com/assets/438922/14151513/1430ad5e-f663-11e5-8a1d-03e3a27ddf18.png)

**Comment by danlipsa** [comment]
https://github.com/UV-CDAT/cdatweb/pull/109

**Comment by mattben** [comment]
Thanks @danlipsa
