### ISSUE TITLE
Multiple view does not work because of a possible bug in VTKWeb

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/cdatweb#58]

**Comment by jbeezley** [comment]
The commit [here](https://github.com/jbeezley/VTK/commit/f14fe4850d420aa502d47a4008830274f841a5ab) fixes the `null` image problem, but there is still a fundamental issue with the global id mechanism.  For one, I think the smart pointer [here](https://github.com/Kitware/VTK/blob/master/Web/Core/vtkObjectIdMap.cxx#L131) should be a weak pointer to allow the view to be freed, but I haven't experimented with it.

**Comment by jbeezley** [comment]
This was fixed a long time ago: https://github.com/UV-CDAT/VTK/pull/1.
