### ISSUE TITLE
Problems with setup

### ISSUE THREAD

**Issue by sterlingbaldwin** [UV-CDAT/cdatweb#72]
I am attempting to setup the vis server locally, so I can work on integrating CDATWeb with the acme-web-fe, but am having some trouble getting python to find the vtk.web module. After building UVCDAT and sourcing my environment, importing vtk.web still gives me an error. In the setup instructions it says:

`
If that gives you an import error, then you need to rebuild VTK or enable the ParaView option for UV-CDAT. It is also possible to compile without ParaView but to enable vtkWeb support. For now this requires patching the UV-CDAT source.
`

But I dont know what that means. How do I rebuild VTK to support vtk.web?

**Comment by jbeezley** [comment]
There is an option for it in the uvcdat setup. It is not on by default.

**Comment by sterlingbaldwin** [comment]
I was unable to use the -DCDAT_BUILD_PARAVIEW=ON flag since for some reason the labs firewall is blocking the terminal from connecting to paraview.org. How do it compile without paraview, but with vtkweb support?

**Comment by jbeezley** [comment]
It doesn't even work with paraview.  You need vtk with something like ENABLE_WEB.

**Comment by sterlingbaldwin** [comment]
That option isnt mentioned in the instructions for [building](http://www.vtk.org/Wiki/VTK/Configure_and_Build#Configure_VTK_with_CMake) vtk. Where did you go to find the setup that worked for you?

**Comment by jbeezley** [comment]
It's a uvcdat option.

**Comment by sterlingbaldwin** [comment]
I dont really know how to use cmake very well, is there somewhere where these options are listed?

**Comment by jbeezley** [comment]
Try ccmake.

**Comment by sterlingbaldwin** [comment]
ah ok I see the option. Ill try rebuilding with it turned on. Thanks!

**Comment by sterlingbaldwin** [comment]
Running the UV-CDAT build with -DCDAT_BUILD_WEB=ON seems to have fixed the problem. Should probably be added to the README.

**Comment by aashish24** [comment]
Done its here: https://github.com/UV-CDAT/cdatweb/pull/73/files

**Comment by sterlingbaldwin** [comment]
There are some other issues I ran into with the setup that arent in the readme, for example in the cdatweb/settings/development.py file, it has a line
`VISUALIZATION_LAUNCHER = 'http://aims1.llnl.gov/vtk'`
Should that be changed to
`VISUALIZATION_LAUNCHER = 'localhost/vtk'`
if Im running locally?

**Comment by aashish24** [comment]
@sterlingbaldwin I will let @jbeezley reply to it. But I agree it would be nice to have it configurable.

**Comment by jbeezley** [comment]
It is configurable, `cdatweb/settings/development.py` is the django configuration file.  I changed it to the aims server a while back so that it would work out of the box.  Let me make a quick change to the readme to go over all the changes necessary to launch it locally.
