### ISSUE TITLE
vis server should always return

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/cdatweb#86]
The vis server should return error and warning messages. We could standardize the returned object.

    {
        "glossary": {
            "response": "Success/Error",
            "warning":"String",
            "plot":"plot"
        }
    }

**Comment by jbeezley** [comment]
It does always return, you just have to attach an error handler like I did in this PR: https://github.com/UV-CDAT/cdatweb/pull/85/files

**Comment by mattben** [comment]
:+1:
