### ISSUE TITLE
hard coded file path

### ISSUE THREAD

**Issue by mattben** [UV-CDAT/cdatweb#95]
currently local_settings stores the path to the 'shared storage' this should be a settable attribute per user

**Comment by jbeezley** [comment]
I don't think it is a particularly good idea to expose the underlying file system to the user.  In particular, the server as it is currently configured is running as root so you at very least giving them read-only access to the entire machine and probably opening the door for them to take over the server outright.  At best, we can have a prefix path as it is currently defined and create a directory under that for files controlled by individual users.

If the goal here is to handle file permissions and access control, I'm hesitant to go down this route at all within the current code base.  My understanding is that the ESGF is intended to manage these issues.  If we really do want to start handling this locally, Kitware develops a full [software stack](http://girder.readthedocs.org/en/latest/) dedicated to it that we can tap into.

**Comment by aashish24** [comment]
@jbeezley @mattben I am thinking that we should use Girder and have it used for both local and remote access. Let's talk about it in the next meeting.

**Comment by mattben** [comment]
@aashish24 what is Grinder? Who makes it?

**Comment by aashish24** [comment]
@mattben its one of the open source software from Kitware (http://girder.readthedocs.org/en/latest/), @jbeezley pointed to it in his comment as well. I am open for other solutions too if you know one.

**Comment by mattben** [comment]
Requirement change.
For server side data storage. 
Their will be the shared storage location (local_settings.py)
and then also a per user (/data/cdatweb/user_id
